class TImages:
    # -- App Logos
    dark_app_logo = "assets/logos/t-store-splash-logo-black.png"
    light_app_logo = "assets/logos/t-store-splash-logo-white.png"

    # -- Social Logos
    google = "assets/logos/google-icon.png"
    facebook = "assets/logos/facebook-icon.png"

    # -- Category Icons
    sport_icon = "assets/icons/categories/icons8-bowling-64.png"
    cloth_icon = "assets/icons/categories/icons8-tailors-dummy-64.png"
    shoe_icon = "assets/icons/categories/icons8-shoes-64.png"
    cosmetics_icon = "assets/icons/categories/icons8-cosmetics-64.png"
    animal_icon = "assets/icons/categories/icons8-dog-heart-64.png"
    toy_icon = "assets/icons/categories/icons8-wooden-toy-car-50.png"
    furniture_icon = "assets/icons/categories/icons8-dining-chair-64.png"
    jewelery_icon = "assets/icons/categories/icons8-sparkling-diamond-64.png"
    electronics_icon = "assets/icons/categories/icons8-smartphone-64.png"

    # -- Brand Icons
    nike_logo = "assets/icons/brands/nike.png"
    adidas_logo = "assets/icons/brands/adidas-logo.png"
    apple_logo = "assets/icons/brands/apple-logo.png"
    jordan_logo = "assets/icons/brands/jordan-logo.png"
    puma_logo = "assets/icons/brands/puma-logo.png"
    zara_logo = "assets/icons/brands/zara-logo.png"
    kenwood_logo = "assets/icons/brands/kenwood-logo.png"
    herman_miller_logo = "assets/icons/brands/herman-miller-logo.png"
    ikea_logo = "assets/icons/brands/ikea_logo.png"
    acer_logo = "assets/icons/brands/acer_logo.png"

    # -- Animations
    products_illustration = "assets/images/animations/sammy-line-workout.gif"
    products_sale_illustration = "assets/images/animations/sammy-line-sale.png"
    static_success_illustration = "assets/images/animations/sammy-line-success.png"
    delivered_in_plane_illustration = "assets/images/animations/sammy-line-come-back-later.png"
    delivered_email_illustration = "assets/images/animations/sammy-line-man-receives-a-mail.png"
    verify_illustration = "assets/images/animations/sammy-line-travel-backpack-with-passport-and-air-ticket.gif"

    # -- OnBoarding Texts
    on_boarding_image1 = "assets/images/on_boarding_images/sammy-line-searching.gif"
    on_boarding_image2 = "assets/images/on_boarding_images/sammy-line-shopping.gif"
    on_boarding_image3 = "assets/images/on_boarding_images/sammy-line-delivery.gif"

    # -- Products
    product_image1 = "assets/images/products/nike-shoes.png"
    product_image2 = "assets/images/products/product-1.png"
    product_image3 = "assets/images/products/product-jacket.png"
    product_image4 = "assets/images/products/product-jeans.png"
    product_image5 = "assets/images/products/product-shirt.png"
    product_image6 = "assets/images/products/product-slippers.png"
    product_image7 = "assets/images/products/NikeAirJOrdonBlackRed.png"
    product_image8 = "assets/images/products/NikeAirJOrdonOrange.png"
    product_image9 = "assets/images/products/NikeAirJordonwhiteMagenta.png"
    product_image10 = "assets/images/products/NikeAirJOrdonWhiteRed.png"
    product_image11 = "assets/images/products/samsung_s9_mobile.png"
    product_image12 = "assets/images/products/samsung_s9_mobile_withback.png"
    product_image13 = "assets/images/products/samsung_s9_mobile_back.png"
    product_image14 = "assets/images/products/iphone8_mobile.png"
    product_image15 = "assets/images/products/iphone8_mobile_back.png"
    product_image16 = "assets/images/products/iphone8_mobile_dual_side.png"
    product_image17 = "assets/images/products/iphone8_mobile_front.png"
    product_image18 = "assets/images/products/tomi_dogfood.png"
    product_image19 = "assets/images/products/NikeAirJordonSingleBlue.png"
    product_image20 = "assets/images/products/NikeAirJordonSingleOrange.png"
    productImage21 = "assets/images/products/NikeAirMax.png"
    productImage22 = "assets/images/products/NikeBasketballShoeGreenBlack.png"
    productImage23 = "assets/images/products/NikeWildhorse.png"
    productImage24 = "assets/images/products/tracksuit_black.png"
    productImage25 = "assets/images/products/tracksuit_blue.png"
    productImage26 = "assets/images/products/tracksuit_red.png"
    productImage27 = "assets/images/products/trcksuit_parrotgreen.png"
    productImage28 = "assets/images/products/Adidas_Football.png"
    productImage29 = "assets/images/products/baseball_bat.png"
    productImage30 = "assets/images/products/cricket_bat.png"
    productImage31 = "assets/images/products/tennis_racket.png"
    productImage32 = "assets/images/products/bedroom_bed.png"
    productImage33 = "assets/images/products/bedroom_lamp.png"
    productImage34 = "assets/images/products/bedroom_sofa.png"
    productImage35 = "assets/images/products/bedroom_wardrobe.png"
    productImage36 = "assets/images/products/kitchen_counter.png"
    productImage37 = "assets/images/products/kitchen_dining table.png"
    productImage38 = "assets/images/products/kitchen_refrigerator.png"
    productImage39 = "assets/images/products/office_chair_1.png"
    productImage40 = "assets/images/products/office_chair_2.png"
    productImage41 = "assets/images/products/office_desk_1.png"
    productImage42 = "assets/images/products/office_desk_2.png"
    productImage43 = "assets/images/products/bedroom_bed_black.png"
    productImage44 = "assets/images/products/bedroom_bed_grey.png"
    productImage45 = "assets/images/products/bedroom_bed_simple_brown.png"
    productImage46 = "assets/images/products/bedroom_bed_with_comforter.png"
    productImage47 = "assets/images/products/acer_laptop_1.png"
    productImage48 = "assets/images/products/acer_laptop_2.png"
    productImage49 = "assets/images/products/acer_laptop_3.png"
    productImage50 = "assets/images/products/acer_laptop_4.png"
    productImage51 = "assets/images/products/iphone_13_pro.png"
    productImage52 = "assets/images/products/iphone_14_pro.png"
    productImage53 = "assets/images/products/iphone_14_white.png"
    productImage54 = "assets/images/products/product-shirt_blue_1.png"
    productImage55 = "assets/images/products/product-shirt_blue_2.png"
    productImage56 = "assets/images/products/acer_laptop_var_1.png"
    productImage57 = "assets/images/products/acer_laptop_var_2.png"
    productImage58 = "assets/images/products/acer_laptop_var_3.png"
    productImage59 = "assets/images/products/acer_laptop_var_4.png"
    productImage60 = "assets/images/products/tshirt_red_collar.png"
    productImage61 = "assets/images/products/tshirt_yellow_collar.png"
    productImage62 = "assets/images/products/tshirt_green_collar.png"
    productImage63 = "assets/images/products/tshirt_blue_collar.png"
    productImage64 = "assets/images/products/leather_jacket_1.png"
    productImage65 = "assets/images/products/leather_jacket_2.png"
    productImage66 = "assets/images/products/leather_jacket_3.png"
    productImage67 = "assets/images/products/leather_jacket_4.png"
    productImage68 = "assets/images/products/tshirt_blue_without_collar_back.png"
    productImage69 = "assets/images/products/tshirt_blue_without_collar_front.png"
    productImage70 = "assets/images/products/iphone_12_red.png"
    productImage71 = "assets/images/products/iphone_12_blue.png"
    productImage72 = "assets/images/products/iphone_12_green.png"
    productImage73 = "assets/images/products/iphone_12_black.png"
    productImage74 = "assets/images/products/slipper-product-1.png"
    productImage75 = "assets/images/products/slipper-product-2.png"
    productImage76 = "assets/images/products/slipper-product-3.png"
    productImage77= "assets/images/products/slipper-product.png"




# -- Product Reviews
    userProfileImage1 = "assets/images/reviews/review_profile_image_1.jpg"
    userProfileImage2 = "assets/images/reviews/review_profile_image_2.jpeg"
    userProfileImage3 = "assets/images/reviews/review_profile_image_3.jpeg"

# -- Banners
    promoBanner1 = "assets/images/products/promo-banner-1.png"
    promoBanner2 = "assets/images/products/promo-banner-2.png"
    promoBanner3 = "assets/images/products/promo-banner-3.png"
    banner1 = "assets/images/banners/banner_1.jpg"
    banner2 = "assets/images/banners/banner_2.jpg"
    banner3 = "assets/images/banners/banner_3.jpg"
    banner4 = "assets/images/banners/banner_4.jpg"
    banner5 = "assets/images/banners/banner_5.jpg"
    banner6 = "assets/images/banners/banner_6.jpg"
    banner7 = "assets/images/banners/banner_7.jpg"
    banner8 = "assets/images/banners/banner_8.jpg"


# -- Profile
    user = "assets/images/content/user.png"

# -- Payment Methods
    applePay = "assets/icons/payment_methods/apple-pay.png"
    googlePay = "assets/icons/payment_methods/google-pay.png"
    creditCard = "assets/icons/payment_methods/credit-card.png"
    masterCard = "assets/icons/payment_methods/master-card.png"
    paypal = "assets/icons/payment_methods/paypal.png"
    visa = "assets/icons/payment_methods/visa.png"
    paystack = "assets/icons/payment_methods/paystack.png"
    paytm = "assets/icons/payment_methods/paytm.png"
    successfulPaymentIcon = "assets/icons/payment_methods/successful_payment_icon.png"